CREATE TABLE IF NOT EXISTS project (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,description VARCHAR(500) NOT NULL DEFAULT '',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS app_user (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,
 display_name VARCHAR(50) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS project_member (
 project_id BIGINT NOT NULL REFERENCES project(id),user_id BIGINT NOT NULL REFERENCES app_user(id),
 role VARCHAR(10) NOT NULL,joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_id,user_id)
);
CREATE TABLE IF NOT EXISTS task (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,project_id BIGINT NOT NULL REFERENCES project(id),title VARCHAR(100) NOT NULL,
 description VARCHAR(2000) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'TODO',priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
 creator_id BIGINT NOT NULL REFERENCES app_user(id),assignee_id BIGINT REFERENCES app_user(id),due_date DATE,
 version INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS task_comment (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,task_id BIGINT NOT NULL REFERENCES task(id),author_id BIGINT NOT NULL REFERENCES app_user(id),
 content VARCHAR(500) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
